### ISSUE TITLE
mathbackground area

### ISSUE THREAD

**Issue by pkra** [mathjax/mathjax-v3#138]
Follow-up question to #137. 

[This is an old question of mine.] 

Is it conceivable to have MathJax v3 (optionally) provide "non-tight" backgrounds, i.e., something closer to the behavior of CSS? 

Or perhaps reversely: is the new layout more stable here to do this manually? E.g., `  <mstyle mathbackground="red" style="line-height: 1em"><mn>1</mn></mstyle>` seems ok from a quick test (but then wouldn't work in an SVG setting).

**Comment by dpvc** [comment]
The change to line-height would adversely affect the output of some math contained in the `mstyle`, particularly vertical staking, like `mfrac` and `munderover` elements. The line-height being set to 0 is important to the rest of the layout.  It might be possible to add more CSS to put back the line-height internally for those cases.

Also, its not clear to me what the exact output is that you want.  It would be possible to make the characters all have the height and depth of the font (which is how text fonts usually work), but then that would affect the layout of things like powers (the position of the square in x^2 would be too high) and roots (`\sqrt{x}` would leave too much room above the x, at least according to TeX layout rules).  Perhaps you only want this when there is a background color?  

To get the positioning correct with full-height characters, however, the bounding box code would have to keep track of both he TeX binding box and the HTML bounding box.  This would complicate both the bounding box code and the layout code (especially if the HTML bounding boxes were the ones actually used).  The original HTML-CSS renderer worked that way, which made it very complicated, and contributes to its slowness (if I recall correctly, the bounding box computations were about 10% of the run time).  One of the v3 goals was to simplify the bounding box handling in order to reduce that time.

**Comment by pkra** [comment]
Thanks for the detailed reply, Davide. Plenty to think about for me.
