### ISSUE TITLE
[TeX input] parse error points to wrong macro

### ISSUE THREAD

**Issue by pkra** [mathjax/mathjax-v3#168]
`\stackrel{x}\mathrel{b}` will give a parse error `Missing argument for \mathrel` when the problem is with stackrel.

This also happens in v2.

**Comment by dpvc** [comment]
Unfortunately, this is the correct error message for this situation, and it is due to the fact that TeX allows unbraced arguments to its macros.  So `\stackrel{x}\mathrel{b}` means effectively `\stackrel{x}{\mathrel}{b}` and that means the `\mathrel` is being processed without its corresponding argument, and that is why you get this message.  (You already figured that out, I'm sure.)  So from TeX's point of view, there is nothing wrong with the `\stackrel` itself: it has all its arguments, and so TeX doesn't see the error as being with `\stackrel`.

This is the case with actual LaTeX itself, as well.  If you process `\[\stackrel{x}\mathrel{b}\]`` in LaTeX you get

```
! Missing { inserted.
<to be read again> 
                   }
l.14 \[\stackrel{x}\mathrel
                           {b}\]
```

Note that the indicated position of the inserted `{` is after the `\mathrel`, meaning that it is complaining that `\mathrel` is missing its argument.  

Turning on `\tracinginmacros` and `\tracingincommands` in LaTeX shows

```
\stackrel #1#2->\mathrel {\mathop {#2}\limits ^{#1}}
#1<-x
#2<-\mathrel 
{\mathrel}
{math mode: \mathop}
{\mathrel}
! Missing { inserted.
<to be read again> 
                   }
l.17 \[\stackrel{x}\mathrel
                           {b}\]
```

indicating that `\stackrel{x}\mathrel{b}` has been replaced by 

```
\mathrel{\mathop{\mathrel}\limits^{x}
```

and that the error message is indeed about the (second) `\mathrel` (which is now `{\mathrel}`) not having its argument.  This also explains the '<to be read again>' comment that says `}` is to be reprocessed after the "missing" `{` has been inserted, since the `\mathrel` is followed by a close brace in the expansion of `\stackrel`.

Because the `\stackrel` macro has already been replaced at this point, the fact that the current string being processed came from `\steckrel` is no longer known, and an error message involving `\stackrel` is not made.

The best that teX (and MathJax) can do is report the fact that `\mathrel` doesn't seem to have its argument.  The fact that that was caused by your forgetting the braces around an argument for some outer macro is something that is beyond its analysis, and something you would have to figure out yourself.  Unfortunately, many of TeX's error messages work that way.  The problem that eventually stops TeX (and that it identifies) may not be the actual flaw in the TeX code.  (I recall many times, for example, that a missing close dollar for a math expression would not be noticed by TeX until the end of the paragraph containing the problem, well after the actual missing delimiter.)

It would be nice if TeX could always point out the cause of the bugs in your TeX source, but that is not really possible.  If it were, then TeX would simply fix the problem for you and go on typesetting the rest of the paper automatically.  But if you have ever allowed TeX to continue after an error, you will know that, most of the time, its attempt to fix the problem was unsuccessful, and only leads to more error messages.  That is why TeX reports what it (often wrongly) thinks is the problem rather than just making its recommended fix.

In the case of this example, inserting the missing brace means that the string being processed is now `\mathrel{\mathop{\mathrel{}\limits^{x}}`, with processing continuing at the `\mathrel{}`, which is followed by `\limits`.  That leads to additional errors:

```
\! Limit controls must follow a math operator.
\stackrel ...mathrel {\mathop {#2}\limits 
                                          ^{#1}}
l.14 \[\stackrel{x}\mathrel
                           {b}\]
```
and continuing again gives
```
! Missing } inserted.
<inserted text> 
                }
l.14 \[\stackrel{x}\mathrel{b}\]                              
```
to eventually balance the open brace that it inserted originally.

Unfortunately, a higher level of understanding is necessary to produce the right correction, and in a macro language like TeX, that is hard to achieve.  I'm afraid that this is the message that is going to be produced in this situation.  There are many other similar cases where a macro is pulled into an argument for another one and loses its own argument in the process.

**Comment by pkra** [comment]
Oh, I think you may have explained this to me once before! I'm sorry for the noise.

Thanks for clarifying once again.

**Comment by dpvc** [comment]
No problem.  It is good to have some of these explanations out there.
