### ISSUE TITLE
support for old displayAlign option

### ISSUE THREAD

**Issue by pkra** [mathjax/mathjax-v3#186]
I couldn't find a reference to it in the source or the demo configurations. Is support for this planned?

In particular, I'm trying to recreate the layout I'd get in v2 when setting displayAlign andTagSide to left while having a container width at 0.

**Comment by dpvc** [comment]
There probably should be something that allows TeX to specify the `indentalign` to use for the constructed `<math>` elements.

For now, you could try

```
import {MmlMath} from 'xyz/mathjax3/core/MmlTree/MmlNodes/math.js';
MmlMath.defaults.indentalign = 'left';
```

I think that should do it.

**Comment by pkra** [comment]
Thanks, Davide.

> There probably should be something that allows TeX to specify the indentalign to use for the constructed <math> elements.

I'm confused by names now. v3's indentalign seems to correspond to v2's displayAlign - which was a Hub option., not a TeX input option. Though the TeX input has TagIndent in v2.

Anyhoo. Overriding the MmlNodes works -- thanks!

**Comment by dpvc** [comment]
> v3's indentalign seems to correspond to v2's displayAlign

Yes and no.  `indentalign` is an attribute of the `<math>` element, and is part of the MathML spec.  It was available in v2, but was not implemented in the first version of HTML-CSS, and I used `displayAlign` (and `displayIndent`) as a mechanism of handling this (it was originally used to set the CSS for the container element).  Once `indentalign`, `indentshift`, and the other related attributes were implemented, the correct way to alignment should have been through them, rather than some non-MathML properties like `dislpayAlign` and `displayIndent`.

The main problem with that is that TeX (and AsciiMath) input don't provide a means of setting those attributes.  The TeX input jax should have a configuration parameter to give a value for `indentalign` by default for the expressions it produces, and there should be a mechanism to override that for specific equations (I don't know if there is a LaTeX way of doing that, but if not, we could use some non-standard macro for it).

I always felt that `displayAlign` and `displayIndent` were a mistake, since their effect was not reflected in the MathML itself, only in the display, which means, for example, that they weren't reflected in the MathML in the Show Math As, so would not be reflected if used in a native MathML setting.  

On the other hand, the default value for `indentalign` is `auto`, so it is up to the renderer how that should be handled, and that does make a `displayAlign` value a reasonable configuration option.  However, `indentshift` has a default value of `0`, so `displayIndent` is less justifiable.  Again, the TeX input jax could have a default value that it uses for `indentshift` on the expressions it produces, however.

So that is what I meant by my (too-short) response.

**Comment by pkra** [comment]
Thanks for the detailed explanation, Davide! I had forgotten about the various indent* properties. Have you ever come across them in plain MathML?

**Comment by dpvc** [comment]
Nope, but I don't look at a lot of MathML from the wild.  You would have more contact with that, and Volker as well, as you guys look at real world examples.

**Comment by pkra** [comment]
Hah, maybe. I don't recall running into it in real world content, mostly in discussions about linebreaking.

**Comment by dpvc** [comment]
I mad a PR (#186) to provide `displayAlign` and `displayIndent` configuration for the SVG and CHTML output jax.  Still need to add control for `indentalign` and `indentshift` to TeX input.
