### ISSUE TITLE
Question regarding esm and pkg

### ISSUE THREAD

**Issue by rysavyjan** [mathjax/mathjax-v3#268]
We are building TeX to PNG converter using your library and would like to pack it using https://github.com/zeit/pkg into standalone executable. Unfortunately pkg doesn't support esm: https://github.com/zeit/pkg/issues?utf8=%E2%9C%93&q=esm

We are receiving following error when we start created executable
```
TypeError: this._checkModeProperty is not a function
    at Object.Stats.isFile (internal/fs/utils.js:288:15)
    at Object.<anonymous> (E:\snapshot\math-renderer\index.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:710:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
```

Do you have any idea how to solve this problem? Should we compile source code using Babel instead of using esm? Is there another option? Thank you.

**Comment by dpvc** [comment]
The issue is not coming from MathJax code.  It looks like it is coming from your `index.js` file while trying to load something.  If your `index.js` is using `import` to do that, it may be that you need to convert to `require()` for that.

There are several ways you can include MathJax into your project, and you don't say which one you are using.  Are you loading MathJax components (from the `components` subdirectory), or are you importing the MathJax files directly?  You can use `require()` to do either one.  For the components, you would need to load the `components/dist` copies, not the source copies.  In either case, the files in `components/dist` and in the `mathjax3/mathjax3` directory are all ES5 modules, so don't include `import` commands themselves, so should not pose a problem for inclusion by `pkg` (though I admit to not having every used `pkg`).  So I'm wondering if this isn't just your `index.js` that is doing the import?

If you need to bundle a custom MathJax configuration, you can do that following the example in the [demos repository](https://github.com/mathjax/mj3-demos/tree/master/custom-build) (see the [documentation](https://github.com/mathjax/mj3-demos/tree/master/custom-build/custom-build.md) for details).  Also, the components like [tex-svg](https://github.com/mathjax/mathjax-v3/tree/beta.4/components/src/tex-svg) provide examples that you could customize as well.  Since these get webpacked into a single `.js` file, you could build that and `require()` it into your project as part of a larger webpack.  It already does the babel conversion, so you would not need to do that yourself.

So it seems to me that the only part that might need babel conversion is your own `index.js` (or other files that you include).  You should be able to handle the MathJax parts without that.

One of the [issues](https://github.com/zeit/pkg/issues/439) you link to suggests that using

    pkg app.js --options experimental-modules

would allow node to process `import` commands.  Did you try that?  Or perhaps using a file that contains

```
require = require('esm')(module)
module.exports = require('./index.js');
```

as your main file would do it (I haven't tested it).

**Comment by rysavyjan** [comment]
Thank you for your time and very detailed response.

My index.js looks exactly how you assumed:
```
require = require("esm")(module)
module.exports = require("./main.js")
```

I'm using MathJax according to https://github.com/mathjax/mj3-demos-node/blob/master/direct/tex2svg
```
//  Load the packages needed for MathJax
const MathJax = require('mathjax3/mathjax3/mathjax.js').MathJax;
const TeX = require('mathjax3/mathjax3/input/tex.js').TeX;
const SVG = require('mathjax3/mathjax3/output/svg.js').SVG;
const liteAdaptor = require('mathjax3/mathjax3/adaptors/liteAdaptor.js').liteAdaptor;
const RegisterHTMLHandler = require('mathjax3/mathjax3/handlers/html.js').RegisterHTMLHandler;
const AllPackages = require('mathjax3/mathjax3/input/tex/AllPackages.js').AllPackages;
...
    //  Create DOM adaptor and register it for HTML documents
    const adaptor = liteAdaptor();
    RegisterHTMLHandler(adaptor);
    //  Create input and output jax and a document using them on the content from the HTML file
    const tex = new TeX({packages: options.packages.split(/\s*,\s*/)});
    const svg = new SVG({fontCache: (options.fontCache ? 'local' : 'none')});
    const html = MathJax.document('', {InputJax: tex, OutputJax: svg});
...
```

Without index.js esm loader I get following error:
```
E:\Source\Fine\math-renderer\node_modules\mathjax3\mathjax3\input\tex\mhchem\mhchem_parser.js:5
export var mhchemParser = {
^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

E:\Source\Fine\math-renderer>
```

So mhchem_parser.js looks like ES6 module?

**Comment by rysavyjan** [comment]
Regarding your question: yes I tried to use `pkg app.js --options experimental-modules`, unfortunately it didn't help. I received the same error message I copied to the my first post.

**Comment by dpvc** [comment]
OK, thanks for the additional information.  I think we are making progress.  Try editing `node_modules\mathjax3\mathjax3\input\tex\mhchem\mhchem_parser.js` and add

```
"use strict";
Object.defineProperty(exports, '__esModule', {value: true});
```

at the top, before anything else, and then change

```
export var mhchemParser = {
```

at line 5 to 

```
exports.mhchemParser = {
```

then

```
export var texify = {
```

at line 1286 to

```
exports.texify = {
```

and finally

```
/** @param {number} a */
export function assertNever(a) {}
/** @param {string} a */
export function assertString(a) {}
```

to 

```
/** @param {number} a */
exports.assertNever = function (a) {}
/** @param {string} a */
exports.assertString = function (a) {}
```

at the very bottom of the file.  That should make it an CommonJS module.

**Comment by dpvc** [comment]
> yes I tried to use `pkg app.js --options experimental-modules`, unfortunately it didn't help.

Did you try it on the `main.js` file rather than the `index.js` file (like you do above to get the error in mhchem parser)?

Did you try `pkg app.js --options require=esm` on your `main.js` file?  (`--require=esm` is a way of avoiding the need for the two-line `index.js` file).  I suspect this won't work, either, but it is worth a try.

**Comment by rysavyjan** [comment]
Regarding your proposed fix, there is following error:
```
e:\Source\Fine\math-renderer\node_modules\mathjax3\mathjax3\input\tex\mhchem\mhchem_parser.js:495
export.mhchemParser.stateMachines = {
^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

I'm going to test pkg with main.js as you suggested, thank you for this tip.

**Comment by dpvc** [comment]
OK, I spoke too quickly, without testing the changes to `mhchem_parser.js`.

Go back to the original version, add the lines

```
"use strict";
Object.defineProperty(exports, '__esModule', {value: true});
```

and remove the `export ` from the four lines that have them (leaving just the `var mhchemParser = {`, and so on).

At the bottom of the file, add

```
exports.mhchemParser = mhchemParser;
exports.texify = texify;
exports.assertNever = assertNever;
exports.assertString = assertString;
```

Note that it is `exports` with an `s`.  I think that should work.

**Comment by rysavyjan** [comment]
Yesss, it work now!

**Comment by rysavyjan** [comment]
OK, I tried pkg on unmodified source code:

```
E:\Source\Fine\math-renderer>pkg -t node10-win-x64 --options require=esm src/main.js
> pkg@4.4.0
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  node_modules\sharp\build\Release
  path-to-executable/sharp/build/Release
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  node_modules\sharp\vendor\lib
  path-to-executable/sharp/vendor/lib
> Warning Failed to make bytecode node10-x64 for file E:\snapshot\math-renderer\node_modules\mathjax3\mathjax3\input\tex\mhchem\mhchem_parser.js

E:\Source\Fine\math-renderer>main.exe
TypeError: this._checkModeProperty is not a function
    at Object.Stats.isFile (internal/fs/utils.js:288:15)
    at startup (internal/bootstrap/node.js:320:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:659:3)
```
```
E:\Source\Fine\math-renderer>pkg -t node10-win-x64 src/main.js
> pkg@4.4.0
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  node_modules\sharp\build\Release
  path-to-executable/sharp/build/Release
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  node_modules\sharp\vendor\lib
  path-to-executable/sharp/vendor/lib
> Warning Failed to make bytecode node10-x64 for file E:\snapshot\math-renderer\node_modules\mathjax3\mathjax3\input\tex\mhchem\mhchem_parser.js

E:\Source\Fine\math-renderer>main.exe
E:\snapshot\math-renderer\node_modules\mathjax3\mathjax3\input\tex\mhchem\mhchem_parser.js:5
export var mhchemParser = {
^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:81:7)
    at createScript (vm.js:276:10)
    at Object.runInThisContext (vm.js:328:10)
    at Module._compile (internal/modules/cjs/loader.js:662:28)
    at Module._compile (pkg/prelude/bootstrap.js:1268:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:710:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:635:17)
```

**Comment by rysavyjan** [comment]
With patched mhchem_parser.js it works fine, server is running:

```
E:\Source\Fine\math-renderer>pkg -t node10-win-x64 src/main.js
> pkg@4.4.0
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  node_modules\sharp\build\Release
  path-to-executable/sharp/build/Release
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  node_modules\sharp\vendor\lib
  path-to-executable/sharp/vendor/lib

E:\Source\Fine\math-renderer>main.exe 3000
Server running at http://127.0.0.1:3000/
```

**Comment by dpvc** [comment]
> Yesss, it works now!

OK, great.  I'll make a pull request to include those changes in the file for the official release.

> I tried pkg on unmodified source code [error messages deleted]

OK, it was worth a try.  Glad the updated `mhchem_parser.js` does the trick!
