### ISSUE TITLE
tsc fails on alpha branch

### ISSUE THREAD

**Issue by pkra** [mathjax/mathjax-v3#81]
With node@8.9.3 and npm@5.6.0, I currently get 

```
$ npx tsc
mathjax3-ts/output/chtml/Wrappers/mfrac.ts(148,71): error TS1005: ')' expected.
mathjax3-ts/output/chtml/Wrappers/mfrac.ts(148,73): error TS1005: ';' expected.
mathjax3-ts/output/chtml/Wrappers/mfrac.ts(148,110): error TS1005: ';' expected.
```

**Comment by pkra** [comment]
I get the same issue on master.

**Comment by dpvc** [comment]
This turns out to bed to shaking versions of typescript from 2.3.* to 2.5.*.  I can fix the one issue in mfrac, but there are additional ones in Volker's TeX parser that he will have to address before we can do the upgrade to a newer version of typescript.  I thought I had tested it, but was accidentally still using 2.3.4 and didn't catch it.

You may need to delete your `package-lock.json` file and and do `npm install` to  get the older version again.

**Comment by pkra** [comment]
Thanks, Davide.
